// Modern RBAC with route mapping
const ROLES = {
  OWNER: 'owner',
  SYS_ADMIN: 'sys_admin',
  ACCOUNTANT: 'accountant',
  CONTROLLER: 'controller',
  RECEPTION: 'reception',
  TECHNICIAN: 'technician',
  PRODUCTION_MANAGER: 'production_manager',
  INVENTORY_MANAGER: 'inventory_manager',
  SALES_REP: 'sales_rep',
  MARKETING_MANAGER: 'marketing_manager',
  POS_CASHIER: 'pos_cashier',
  SUPPORT_AGENT: 'support_agent'
};

const PERMISSIONS = {
  USER_MANAGE: 'user.manage',
  ROLE_MANAGE: 'role.manage',
  AUDIT_VIEW: 'audit.view',
  SETTINGS_MANAGE: 'settings.manage',
  CUSTOMER_MANAGE: 'customer.manage',
  CUSTOMER_VIEW: 'customer.view',
  LEAD_MANAGE: 'lead.manage',
  QUOTE_MANAGE: 'quote.manage',
  QUOTE_VIEW: 'quote.view',
  QUOTE_APPROVE: 'quote.approve',
  ORDER_UPDATE: 'order.update',
  ORDER_VIEW: 'order.view',
  WORKORDER_CREATE: 'workorder.create',
  WORKORDER_UPDATE: 'workorder.update',
  WORKORDER_VIEW: 'workorder.view',
  WORKLOG_CREATE: 'worklog.create',
  INVENTORY_MANAGE: 'inventory.manage',
  MATERIAL_VIEW: 'material.view',
  SUPPLIER_VIEW: 'supplier.view',
  INVOICE_CREATE: 'invoice.create',
  INVOICE_VIEW: 'invoice.view',
  INVOICE_SEND: 'invoice.send',
  PAYMENT_CREATE: 'payment.create',
  PAYMENT_VIEW: 'payment.view',
  PAYMENT_REFUND: 'payment.refund',
  POS_CREATE: 'pos.create',
  JOURNAL_CREATE: 'journal.create',
  CAMPAIGN_MANAGE: 'campaign.manage',
  CAMPAIGN_LAUNCH: 'campaign.launch',
  AD_CREATE: 'ad.create',
  AD_VIEW: 'ad.view',
  AD_EDIT: 'ad.edit',
  AD_DELETE: 'ad.delete',

  CONVERSATION_VIEW: 'conversation.view',
  MESSAGE_SEND: 'message.send',
  REPORT_VIEW: 'report.view',
  AI_VIEW: 'ai.view',
  FILE_UPLOAD: 'file.upload',
  FILE_VIEW: 'file.view'
};

// Route to permission mapping (paths without /api prefix)
const ROUTE_PERMISSIONS = {
  // Auth routes (public)
  'POST /login': [],
  'POST /forgot-password': [],
  'POST /reset-password': [],
  
  // Products routes (public GET, protected POST/PUT/DELETE)
  'GET /products': [],
  'GET /products/:id': [],
  'POST /products': [PERMISSIONS.INVENTORY_MANAGE],
  'PUT /products/:id': [PERMISSIONS.INVENTORY_MANAGE],
  'DELETE /products/:id': [PERMISSIONS.INVENTORY_MANAGE],
  
  // User management (auth routes)
  'GET /users': [PERMISSIONS.USER_MANAGE],
  'POST /users': [PERMISSIONS.USER_MANAGE],
  'GET /users/:id': [PERMISSIONS.USER_MANAGE],
  'PUT /users/:id': [PERMISSIONS.USER_MANAGE],
  'DELETE /users/:id': [PERMISSIONS.USER_MANAGE],
  'PUT /users/:id/password': [PERMISSIONS.USER_MANAGE],
  
  // Customer management (auth routes - same pattern as users)
  'GET /customers': [PERMISSIONS.CUSTOMER_VIEW],
  'POST /customers': [PERMISSIONS.CUSTOMER_MANAGE],
  'GET /customers/:id': [PERMISSIONS.CUSTOMER_VIEW],
  'PUT /customers/:id': [PERMISSIONS.CUSTOMER_MANAGE],
  'DELETE /customers/:id': [PERMISSIONS.CUSTOMER_MANAGE],

  
  // Lead management
  'GET /leads': [PERMISSIONS.LEAD_MANAGE],
  'POST /leads': [PERMISSIONS.LEAD_MANAGE],
  'GET /leads/:id': [PERMISSIONS.LEAD_MANAGE],
  'PUT /leads/:id': [PERMISSIONS.LEAD_MANAGE],
  'DELETE /leads/:id': [PERMISSIONS.LEAD_MANAGE],
  'GET /leads/test': [PERMISSIONS.LEAD_MANAGE],
  'GET /leads/customer/:customerId': [PERMISSIONS.LEAD_MANAGE],
  
  // Quote management
  'GET /quotes': [PERMISSIONS.QUOTE_VIEW],
  'POST /quotes': [PERMISSIONS.QUOTE_MANAGE],
  'GET /quotes/:id': [PERMISSIONS.QUOTE_VIEW],
  'PUT /quotes/:id': [PERMISSIONS.QUOTE_MANAGE],
  'POST /quotes/:id/approve': [PERMISSIONS.QUOTE_APPROVE],
  
  // Order management
  'GET /orders': [PERMISSIONS.ORDER_VIEW],
  'GET /orders/:id': [PERMISSIONS.ORDER_VIEW],
  'PUT /orders/:id': [PERMISSIONS.ORDER_UPDATE],
  'GET /orders/ready-for-communication': [PERMISSIONS.ORDER_VIEW],
  
  // Production (paths after /api/production mount point)
  'GET /work-orders': [PERMISSIONS.WORKORDER_VIEW],
  'GET /work-orders/:id': [PERMISSIONS.WORKORDER_VIEW],
  'POST /work-orders': [PERMISSIONS.WORKORDER_CREATE],
  'PUT /work-orders/:id': [PERMISSIONS.WORKORDER_UPDATE],
  'POST /work-logs': [PERMISSIONS.WORKLOG_CREATE],
  'GET /work-logs': [PERMISSIONS.WORKORDER_VIEW],
  'PUT /orders/:id/status': [PERMISSIONS.ORDER_UPDATE],
  'POST /orders/:id/issue-materials': [PERMISSIONS.WORKORDER_UPDATE],
  
  // Inventory
  'GET /materials': [PERMISSIONS.MATERIAL_VIEW],
  'POST /materials': [PERMISSIONS.INVENTORY_MANAGE],
  'GET /materials/:id': [PERMISSIONS.MATERIAL_VIEW],
  'PUT /materials/:id': [PERMISSIONS.INVENTORY_MANAGE],
  'DELETE /materials/:id': [PERMISSIONS.INVENTORY_MANAGE],
  'GET /suppliers': [PERMISSIONS.SUPPLIER_VIEW],
  'POST /suppliers': [PERMISSIONS.INVENTORY_MANAGE],
  'GET /suppliers/:id': [PERMISSIONS.SUPPLIER_VIEW],
  'PUT /suppliers/:id': [PERMISSIONS.INVENTORY_MANAGE],
  'DELETE /suppliers/:id': [PERMISSIONS.INVENTORY_MANAGE],
  'GET /stock-movements': [PERMISSIONS.MATERIAL_VIEW],
  'POST /stock-movements': [PERMISSIONS.INVENTORY_MANAGE],
  'GET /purchase-orders': [PERMISSIONS.INVENTORY_MANAGE],
  'POST /purchase-orders': [PERMISSIONS.INVENTORY_MANAGE],
  'GET /purchase-orders/:id': [PERMISSIONS.INVENTORY_MANAGE],
  'PUT /purchase-orders/:id': [PERMISSIONS.INVENTORY_MANAGE],
  
  // Finance - Invoices
  'GET /invoices': [PERMISSIONS.INVOICE_VIEW],
  'POST /invoices': [PERMISSIONS.INVOICE_CREATE],
  'GET /invoices/:id': [PERMISSIONS.INVOICE_VIEW],
  'PUT /invoices/:id': [PERMISSIONS.INVOICE_CREATE],
  
  // Finance - Payments
  'GET /payments': [PERMISSIONS.PAYMENT_VIEW],
  'POST /payments': [PERMISSIONS.PAYMENT_CREATE],
  'GET /payments/:id': [PERMISSIONS.PAYMENT_VIEW],
  'POST /payments/lanari': [PERMISSIONS.PAYMENT_CREATE],
  'GET /payments/:id/status': [PERMISSIONS.PAYMENT_VIEW],
  'PUT /payments/:payment_id/refund': [PERMISSIONS.PAYMENT_REFUND],
  
  // Finance - POS
  'POST /pos-sales': [PERMISSIONS.POS_CREATE],
  'GET /pos-sales': [PERMISSIONS.POS_CREATE],
  
  // Finance - Journal Entries
  'POST /journal-entries': [PERMISSIONS.JOURNAL_CREATE],
  'GET /journal-entries': [PERMISSIONS.JOURNAL_CREATE],
  'GET /journal-entries/:id': [PERMISSIONS.JOURNAL_CREATE],
  'GET /chart-of-accounts': [PERMISSIONS.JOURNAL_CREATE],
  
  // Marketing
  'GET /campaigns': [PERMISSIONS.CAMPAIGN_MANAGE],
  'POST /campaigns': [PERMISSIONS.CAMPAIGN_MANAGE],
  'GET /campaigns/:id': [PERMISSIONS.CAMPAIGN_MANAGE],
  'GET /campaigns/:id/performance': [PERMISSIONS.CAMPAIGN_MANAGE],
  'POST /campaigns/:id/launch': [PERMISSIONS.CAMPAIGN_LAUNCH],
  'POST /broadcast/all': [PERMISSIONS.CAMPAIGN_MANAGE],
  'POST /broadcast/segment': [PERMISSIONS.CAMPAIGN_MANAGE],
  'POST /email': [PERMISSIONS.MESSAGE_SEND],
  
  // Ads Management
  'GET /ads/public': [],
  'POST /ads/public/:id/impression': [],
  'POST /ads/public/:id/click': [],
  'GET /ads': [PERMISSIONS.AD_VIEW],
  'GET /ads/:id': [PERMISSIONS.AD_VIEW],
  'POST /ads': [PERMISSIONS.AD_CREATE],
  'PUT /ads/:id': [PERMISSIONS.AD_EDIT],
  'DELETE /ads/:id': [PERMISSIONS.AD_DELETE],
  'PATCH /ads/:id/toggle': [PERMISSIONS.AD_EDIT],
  
  // Communications
  'GET /conversations': [PERMISSIONS.CONVERSATION_VIEW],
  'GET /conversations/:id': [PERMISSIONS.CONVERSATION_VIEW],
  'POST /conversations/:id/messages': [PERMISSIONS.MESSAGE_SEND],
  'PUT /conversations/:id/status': [PERMISSIONS.CONVERSATION_VIEW],
  
  // AI & Analytics
  'GET /predictions/demand': [PERMISSIONS.AI_VIEW],
  'GET /predictions/churn': [PERMISSIONS.AI_VIEW],
  'GET /predictions/segments': [PERMISSIONS.AI_VIEW],
  'GET /predictions/pricing': [PERMISSIONS.AI_VIEW],
  'GET /reorder-suggestions': [PERMISSIONS.AI_VIEW],
  'GET /customer-insights': [PERMISSIONS.AI_VIEW],
  
  // Reports
  'GET /reports/sales': [PERMISSIONS.REPORT_VIEW],
  'GET /reports/inventory': [PERMISSIONS.REPORT_VIEW],
  'GET /reports/financial': [PERMISSIONS.REPORT_VIEW],
  'GET /reports/production': [PERMISSIONS.REPORT_VIEW],
  
  // Files
  'POST /upload/artwork': [PERMISSIONS.FILE_UPLOAD],
  'GET /files/:id': [PERMISSIONS.FILE_VIEW],
  
  // Payment routes (mounted at /payments)
  'GET /': [PERMISSIONS.PAYMENT_VIEW],
  'POST /lanari': [PERMISSIONS.PAYMENT_CREATE],
  'PUT /:payment_id/refund': [PERMISSIONS.PAYMENT_REFUND]
};

// Role permission matrix
const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),
  [ROLES.SYS_ADMIN]: [PERMISSIONS.USER_MANAGE, PERMISSIONS.ROLE_MANAGE, PERMISSIONS.AUDIT_VIEW, PERMISSIONS.SETTINGS_MANAGE, PERMISSIONS.REPORT_VIEW],
  [ROLES.ACCOUNTANT]: [PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_VIEW, PERMISSIONS.INVOICE_SEND, PERMISSIONS.PAYMENT_CREATE, PERMISSIONS.PAYMENT_VIEW, PERMISSIONS.PAYMENT_REFUND, PERMISSIONS.JOURNAL_CREATE, PERMISSIONS.REPORT_VIEW, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.ORDER_VIEW, PERMISSIONS.POS_CREATE, PERMISSIONS.MATERIAL_VIEW],
  [ROLES.CONTROLLER]: [PERMISSIONS.ORDER_VIEW, PERMISSIONS.WORKORDER_VIEW, PERMISSIONS.INVOICE_VIEW, PERMISSIONS.PAYMENT_VIEW, PERMISSIONS.REPORT_VIEW, PERMISSIONS.MATERIAL_VIEW, PERMISSIONS.SUPPLIER_VIEW, PERMISSIONS.AI_VIEW],
  [ROLES.RECEPTION]: [
    PERMISSIONS.CUSTOMER_MANAGE, 
    PERMISSIONS.CUSTOMER_VIEW, 
    PERMISSIONS.LEAD_MANAGE, 
    PERMISSIONS.QUOTE_MANAGE, 
    PERMISSIONS.QUOTE_VIEW, 
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.WORKORDER_VIEW, 
    PERMISSIONS.POS_CREATE, 
    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_SEND,
    PERMISSIONS.MESSAGE_SEND, 
    PERMISSIONS.CONVERSATION_VIEW, 
    PERMISSIONS.FILE_UPLOAD, 
    PERMISSIONS.FILE_VIEW
  ],
  [ROLES.TECHNICIAN]: [PERMISSIONS.ORDER_VIEW, PERMISSIONS.ORDER_UPDATE, PERMISSIONS.WORKORDER_VIEW, PERMISSIONS.WORKORDER_UPDATE, PERMISSIONS.WORKLOG_CREATE, PERMISSIONS.MATERIAL_VIEW, PERMISSIONS.QUOTE_VIEW, PERMISSIONS.FILE_VIEW],
  [ROLES.PRODUCTION_MANAGER]: [PERMISSIONS.WORKORDER_CREATE, PERMISSIONS.WORKORDER_UPDATE, PERMISSIONS.WORKORDER_VIEW, PERMISSIONS.WORKLOG_CREATE, PERMISSIONS.ORDER_VIEW, PERMISSIONS.ORDER_UPDATE, PERMISSIONS.MATERIAL_VIEW, PERMISSIONS.SUPPLIER_VIEW, PERMISSIONS.REPORT_VIEW, PERMISSIONS.FILE_VIEW, PERMISSIONS.QUOTE_VIEW, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.INVENTORY_MANAGE, PERMISSIONS.USER_MANAGE],
  [ROLES.INVENTORY_MANAGER]: [PERMISSIONS.INVENTORY_MANAGE, PERMISSIONS.MATERIAL_VIEW, PERMISSIONS.SUPPLIER_VIEW, PERMISSIONS.REPORT_VIEW],
  [ROLES.SALES_REP]: [PERMISSIONS.CUSTOMER_MANAGE, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.LEAD_MANAGE, PERMISSIONS.QUOTE_MANAGE, PERMISSIONS.QUOTE_VIEW, PERMISSIONS.QUOTE_APPROVE, PERMISSIONS.ORDER_VIEW, PERMISSIONS.POS_CREATE, PERMISSIONS.MATERIAL_VIEW, PERMISSIONS.MESSAGE_SEND, PERMISSIONS.CONVERSATION_VIEW, PERMISSIONS.INVOICE_VIEW, PERMISSIONS.PAYMENT_VIEW, PERMISSIONS.REPORT_VIEW],
  [ROLES.MARKETING_MANAGER]: [PERMISSIONS.CAMPAIGN_MANAGE, PERMISSIONS.CAMPAIGN_LAUNCH, PERMISSIONS.AD_CREATE, PERMISSIONS.AD_VIEW, PERMISSIONS.AD_EDIT, PERMISSIONS.AD_DELETE, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.LEAD_MANAGE, PERMISSIONS.REPORT_VIEW, PERMISSIONS.AI_VIEW],
  'marketing': [PERMISSIONS.CAMPAIGN_MANAGE, PERMISSIONS.CAMPAIGN_LAUNCH, PERMISSIONS.AD_CREATE, PERMISSIONS.AD_VIEW, PERMISSIONS.AD_EDIT, PERMISSIONS.AD_DELETE, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.LEAD_MANAGE, PERMISSIONS.REPORT_VIEW, PERMISSIONS.AI_VIEW],
  [ROLES.POS_CASHIER]: [PERMISSIONS.POS_CREATE, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.PAYMENT_CREATE, PERMISSIONS.PAYMENT_VIEW, PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_VIEW, PERMISSIONS.INVOICE_SEND],
  [ROLES.SUPPORT_AGENT]: [PERMISSIONS.CONVERSATION_VIEW, PERMISSIONS.MESSAGE_SEND, PERMISSIONS.CUSTOMER_VIEW, PERMISSIONS.FILE_VIEW, PERMISSIONS.ORDER_VIEW, PERMISSIONS.FILE_UPLOAD]
};

export { ROLES, PERMISSIONS, ROUTE_PERMISSIONS, ROLE_PERMISSIONS };